add check Dockerfile

diff --git a/.pipeline/task-containerize.yaml b/.pipeline/task-containerize.yaml
--- a/.pipeline/task-containerize.yaml
+++ b/.pipeline/task-containerize.yaml
@@ -51,10 +51,50 @@ spec:
     - name: check-dockerfile
       image: alpine/git
       env:
+      - name: DOCKER_FILE
+        value: 'Dockerfile'
+      - name: DOCKER_ROOT
+        value: '/artifacts/'
       command: ["/bin/sh", "-c"]
       args:
-      - set -e -o pipefail;
-        echo "Check Dockerfile placeholder";
+        - |
+          apk add --update npm
+          set -e -o pipefail;
+          npm --version
+          echo "Check Dockerfile placeholder"
+          ls /artifacts
+          ls
+          # Input env variables (can be received via a pipeline environment properties.file.
+          echo "DOCKER_ROOT=${DOCKER_ROOT}"
+          echo "DOCKER_FILE=${DOCKER_FILE}"
+
+          # View build properties
+          if [ -f /artifacts/build.properties ]; then 
+            echo "build.properties:"
+            cat /artifacts/build.properties | grep -v -i password
+          else 
+            echo "build.properties : not found"
+          fi 
+          # also run 'env' command to find all available env variables
+          # or learn more about the available environment variables at:
+          # https://cloud.ibm.com/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
+
+          echo "=========================================================="
+          echo "Checking for Dockerfile at the repository root"
+          if [ -z "${DOCKER_ROOT}" ]; then DOCKER_ROOT=. ; fi
+          if [ -z "${DOCKER_FILE}" ]; then DOCKER_FILE=Dockerfile ; fi
+          if [ -f ${DOCKER_ROOT}/${DOCKER_FILE} ]; then 
+              echo -e "Dockerfile found at: ${DOCKER_FILE}"
+          else
+              echo "Dockerfile not found at: ${DOCKER_FILE}"
+              exit 1
+          fi
+          echo "Linting Dockerfile"
+          npm install -g dockerlint
+          dockerlint -f ${DOCKER_ROOT}/${DOCKER_FILE}
+      volumeMounts:
+        - mountPath: /artifacts
+          name: task-volume
     - name: check-registry
       image: ibmcom/pipeline-base-image
       workingDir: /steps
